# Generated by Django 6.0.2 on 2026-03-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('contato_nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato Principal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Corporativo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo / Novo'), ('negociacao', 'Em Negociação'), ('andamento', 'Em Andamento (Reativar)'), ('inviavel', 'Inviável / Não Avançou')], default='ativo', max_length=20, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='OS nº')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('velocidade', models.CharField(default='50 Mbps', max_length=50, verbose_name='Velocidade')),
                ('tecnologia', models.CharField(default='Fibra', max_length=50, verbose_name='Tecnologia')),
                ('disponibilidade', models.CharField(default='99,50%', max_length=10, verbose_name='Disponibilidade (%)')),
                ('mttr', models.IntegerField(default=4, verbose_name='MTTR (hs)')),
                ('perda_pacote', models.CharField(default='<1%', max_length=10, verbose_name='Perda de Pacote')),
                ('interfaces', models.CharField(default='Gigabit Ethernet (elétrica)', max_length=100, verbose_name='Interfaces')),
                ('ipv4_bloco', models.CharField(default='IPv4 bloco/30', max_length=50, verbose_name='IPs (bloco)')),
                ('trunk', models.CharField(default='Não', max_length=3, verbose_name='Interface em Trunk?')),
                ('dhcp', models.CharField(default='Sim', max_length=3, verbose_name='DHCP habilitado?')),
                ('latencia', models.IntegerField(default=50, verbose_name='Latência (ms)')),
                ('prazo_ativacao', models.IntegerField(default=15, verbose_name='Prazo de Ativação (dias)')),
                ('contato_suporte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato para Suporte')),
                ('telefone_suporte', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número do Telefone')),
                ('inst_endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Instalação')),
                ('inst_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Instalação')),
                ('inst_cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP Instalação')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal')),
                ('taxa_instalacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa Instalação')),
                ('tempo_contrato', models.IntegerField(default=24, verbose_name='Tempo Contrato (meses)')),
                ('email_faturamento', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Faturamento')),
                ('valor_parceiro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago ao parceiro')),
                ('data_ativacao', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('client_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='clientes.endereco', verbose_name='Unidade de Instalação')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='clientes.cliente')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-id'],
            },
        ),
    ]
