# Generated by Django 6.0.2 on 2026-02-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=20, verbose_name='CNPJ/CPF')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('contato_nome', models.CharField(max_length=100, verbose_name='Pessoa de Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_ativacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_ativacao'],
            },
        ),
    ]
