# Generated by Django 6.0.2 on 2026-02-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-data_ativacao'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AddField(
            model_name='partner',
            name='data_emissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='partner',
            name='disponibilidade',
            field=models.CharField(default='99,50%', max_length=10, verbose_name='Disponibilidade (%)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email_faturamento',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Cobrança'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inst_cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP Instalação'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inst_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Instalação'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inst_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Instalação'),
        ),
        migrations.AddField(
            model_name='partner',
            name='interfaces',
            field=models.CharField(default='Gigabit Ethernet', max_length=100, verbose_name='Interfaces'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ipv4_bloco',
            field=models.CharField(default='IPv4 bloco/30', max_length=50, verbose_name='IPs (bloco)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='mttr',
            field=models.IntegerField(default=4, verbose_name='MTTR (hs)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='os_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OS nº'),
        ),
        migrations.AddField(
            model_name='partner',
            name='perda_pacote',
            field=models.CharField(default='<1%', max_length=10, verbose_name='Perda de Pacote'),
        ),
        migrations.AddField(
            model_name='partner',
            name='taxa_instalacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa Instalação'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tecnologia',
            field=models.CharField(default='Fibra', max_length=50, verbose_name='Tecnologia'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tempo_contrato',
            field=models.IntegerField(default=24, verbose_name='Tempo Contrato (meses)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='velocidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidade (Mbps)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='cnpj_cpf',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contato_nome',
            field=models.CharField(max_length=100, verbose_name='Contato'),
        ),
    ]
