# Generated by Django 6.0.2 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Analise'), ('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='analise', max_length=20, verbose_name='Status da Proposta'),
        ),
    ]
