# Generated by Django 6.0.2 on 2026-02-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_options_partner_data_emissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='dhcp',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=3, verbose_name='DHCP habilitado?'),
        ),
        migrations.AddField(
            model_name='partner',
            name='latencia',
            field=models.IntegerField(default=50, verbose_name='Latência (ms)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='prazo_ativacao',
            field=models.IntegerField(default=15, verbose_name='Prazo de Ativação (dias)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='trunk',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Interface em Trunk?'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='interfaces',
            field=models.CharField(default='Gigabit Ethernet (elétrica)', max_length=100, verbose_name='Interfaces'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='velocidade',
            field=models.CharField(default='50 Mbps', max_length=50, verbose_name='Velocidade'),
        ),
    ]
