# Generated by Django 6.0.2 on 2026-02-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_dhcp_partner_latencia_partner_prazo_ativacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-id'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='email_faturamento',
        ),
        migrations.AddField(
            model_name='partner',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.CharField(default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ativação'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='dhcp',
            field=models.CharField(default='Sim', max_length=3, verbose_name='DHCP habilitado?'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='trunk',
            field=models.CharField(default='Não', max_length=3, verbose_name='Interface em Trunk?'),
        ),
    ]
