# Generated by Django 6.0.2 on 2026-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email_faturamento',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Faturamento'),
        ),
    ]
