# Generated by Django 6.0.2 on 2026-03-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_email_faturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ/CPF'),
        ),
    ]
