# Generated by Django 6.0.2 on 2026-03-01 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_alter_partner_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='data_ativacao',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='dhcp',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='email_faturamento',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='inst_cep',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='inst_cidade',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='inst_endereco',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='interfaces',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ipv4_bloco',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='latencia',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='mttr',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='os_numero',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='perda_pacote',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='prazo_ativacao',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='taxa_instalacao',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='tecnologia',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='tempo_contrato',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='trunk',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='valor_mensal',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='velocidade',
        ),
        migrations.AddField(
            model_name='partner',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato Principal'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Corporativo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='OS nº')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('velocidade', models.CharField(default='50 Mbps', max_length=50, verbose_name='Velocidade')),
                ('tecnologia', models.CharField(default='Fibra', max_length=50, verbose_name='Tecnologia')),
                ('disponibilidade', models.CharField(default='99,50%', max_length=10, verbose_name='Disponibilidade (%)')),
                ('mttr', models.IntegerField(default=4, verbose_name='MTTR (hs)')),
                ('perda_pacote', models.CharField(default='<1%', max_length=10, verbose_name='Perda de Pacote')),
                ('interfaces', models.CharField(default='Gigabit Ethernet (elétrica)', max_length=100, verbose_name='Interfaces')),
                ('ipv4_bloco', models.CharField(default='IPv4 bloco/30', max_length=50, verbose_name='IPs (bloco)')),
                ('trunk', models.CharField(default='Não', max_length=3, verbose_name='Interface em Trunk?')),
                ('dhcp', models.CharField(default='Sim', max_length=3, verbose_name='DHCP habilitado?')),
                ('latencia', models.IntegerField(default=50, verbose_name='Latência (ms)')),
                ('prazo_ativacao', models.IntegerField(default=15, verbose_name='Prazo de Ativação (dias)')),
                ('inst_endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Instalação')),
                ('inst_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Instalação')),
                ('inst_cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP Instalação')),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mensal')),
                ('taxa_instalacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taxa Instalação')),
                ('tempo_contrato', models.IntegerField(default=24, verbose_name='Tempo Contrato (meses)')),
                ('email_faturamento', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Faturamento')),
                ('data_ativacao', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='partners.partner', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-id'],
            },
        ),
    ]
