# Generated by Django 6.0.2 on 2026-03-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_endereco_estado_alter_endereco_tipo'),
        ('partners', '0007_alter_partner_options_remove_partner_data_ativacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='partners.partner'),
        ),
    ]
