# Generated by Django 6.0.2 on 2026-03-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_endereco_estado_alter_endereco_tipo'),
        ('partners', '0008_proposal_cliente_alter_proposal_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='clientes.endereco', verbose_name='Unidade de Instalação'),
        ),
    ]
