# Generated by Django 6.0.2 on 2026-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_proposal_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='contato_suporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato para Suporte'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='telefone_suporte',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Número do Telefone'),
        ),
    ]
