# Generated by Django 6.0.2 on 2026-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_proposal_contato_suporte_proposal_telefone_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='valor_parceiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago ao Parceiro'),
        ),
    ]
