# Generated by Django 6.0.2 on 2026-03-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_proposal_valor_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='valor_parceiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago ao parceiro'),
        ),
    ]
