# Generated by Django 6.0.2 on 2026-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_alter_proposal_valor_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo / Novo'), ('negociacao', 'Em Negociação'), ('andamento', 'Em Andamento (Reativar)'), ('inviavel', 'Inviável / Não Avançou')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
