# Generated by Django 6.0.2 on 2026-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_alter_partner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='partner',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='partner',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='Site'),
        ),
    ]
