# Generated by Django 6.0.2 on 2026-04-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0019_proposal_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-id'], 'verbose_name': 'Cotação', 'verbose_name_plural': 'Cotações'},
        ),
        migrations.AlterModelOptions(
            name='proposalmotivoinviavel',
            options={'ordering': ['nome'], 'verbose_name': 'Motivo de Cotação Inviável', 'verbose_name_plural': 'Motivos de Cotações Inviáveis'},
        ),
        migrations.AddField(
            model_name='proposal',
            name='dupla_abordagem',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Dupla Abordagem'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='entrega_rb',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Entrega RB'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='tipo_acesso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Acesso'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='codigo_proposta',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Código da Cotação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='grupo_proposta_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Grupo da Cotação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='ipv4_bloco',
            field=models.CharField(default='IPv4 bloco/30', max_length=50, verbose_name='Bloco IP'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='motivo_inviavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='partners.proposalmotivoinviavel', verbose_name='Motivo da Cotação Inviável'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='nome_proposta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Cotação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='observacao_inviavel',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observação da Cotação Inviável'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Negociação'), ('ativa', 'Viavel'), ('aguardando_contratacao', 'Aguardando Contratação'), ('contratado', 'Contratado'), ('declinado', 'Declinado'), ('encerrada', 'Inviavel')], default='analise', max_length=30, verbose_name='Status da Cotação'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tecnologia',
            field=models.CharField(default='Fibra', max_length=50, verbose_name='Tecnologia de Acesso'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='velocidade',
            field=models.CharField(default='50 Mbps', max_length=50, verbose_name='Velocidade (Mbps)'),
        ),
    ]
