# Generated by Django 6.0.2 on 2026-04-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_confianca_alter_lead_endereco_and_more'),
        ('partners', '0023_partnerplan_valor_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='leads.lead', verbose_name='Lead de Origem'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='lead_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='leads.leadendereco', verbose_name='Endereço do Lead'),
        ),
    ]
