# Generated by Django 6.0.2 on 2026-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_financeiro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tecnico',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
        migrations.AddField(
            model_name='user',
            name='is_gestor',
            field=models.BooleanField(default=False, verbose_name='É Gestor?'),
        ),
    ]
