# Generated by Django 6.0.2 on 2026-03-20 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohistorico',
            options={'ordering': ['-data'], 'verbose_name': 'Registro de Histórico', 'verbose_name_plural': 'Registros de Histórico'},
        ),
        migrations.RenameField(
            model_name='registrohistorico',
            old_name='criado_por',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='acao',
            field=models.TextField(blank=True, null=True, verbose_name='Ação/Descrição'),
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
