# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registrohistorico_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(choices=[('logins_ixc', 'Logins IXC'), ('atendimento_ixc', 'Atendimento IXC'), ('buscar_fornecedores', 'Buscar Fornecedores')], max_length=40, verbose_name='Integracao')),
                ('action', models.CharField(choices=[('download_modelo', 'Download do Modelo'), ('importacao_planilha', 'Importacao da Planilha'), ('execucao_integracao', 'Execucao da Integracao')], max_length=40, verbose_name='Acao')),
                ('arquivo_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Arquivo')),
                ('total_registros', models.PositiveIntegerField(default=0, verbose_name='Total de Registros')),
                ('total_sucessos', models.PositiveIntegerField(default=0, verbose_name='Total de Sucessos')),
                ('total_erros', models.PositiveIntegerField(default=0, verbose_name='Total de Erros')),
                ('detalhes_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audits', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Integracao',
                'verbose_name_plural': 'Logs de Integracoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha_numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='Linha')),
                ('status', models.CharField(choices=[('importado', 'Importado'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='importado', max_length=20, verbose_name='Status')),
                ('mensagem', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('dados_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados Importados')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.integrationaudit', verbose_name='Log')),
            ],
            options={
                'verbose_name': 'Item do Log de Integracao',
                'verbose_name_plural': 'Itens do Log de Integracao',
                'ordering': ['id'],
            },
        ),
    ]
