# Generated by Django 6.0.2 on 2026-03-05 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_user_options_remove_user_is_financeiro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comentario', 'Comentário Manual'), ('anexo', 'Documento Anexado'), ('sistema', 'Log Automático do Sistema')], default='comentario', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Texto do comentário ou descrição do log', null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='historicos_anexos/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Histórico',
                'verbose_name_plural': 'Registros de Histórico',
                'ordering': ['-criado_em'],
            },
        ),
    ]
