# Generated by Django 6.0.2 on 2026-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohistorico',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
