# Generated by Django 6.0.2 on 2026-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_integrationaudit_integrationaudititem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrohistorico',
            options={'ordering': ['-data'], 'verbose_name': 'Registro de Historico', 'verbose_name_plural': 'Registros de Historico'},
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='acao',
            field=models.TextField(blank=True, null=True, verbose_name='Acao/Descricao'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='tipo',
            field=models.CharField(choices=[('comentario', 'Comentario Manual'), ('anexo', 'Documento Anexado'), ('sistema', 'Log Automatico do Sistema')], default='comentario', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Endereco de E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_gestor',
            field=models.BooleanField(default=False, verbose_name='E Gestor?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Usuario'),
        ),
    ]
