# Generated by Django 6.0.2 on 2026-05-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_emailcotacaorespostasync_emailcotacaorespostaimportacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationaudit",
            name="integration",
            field=models.CharField(
                choices=[
                    ("logins_ixc", "Logins IXC"),
                    ("atendimento_ixc", "Atendimento IXC"),
                    ("desativacao_atendimento_ixc", "Desativacao de Atendimento IXC"),
                    ("buscar_fornecedores", "Buscar Fornecedores"),
                    ("importador_leads", "Importador de Leads"),
                ],
                max_length=40,
                verbose_name="Integracao",
            ),
        ),
    ]
