# Generated by Django 6.0.2 on 2026-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inativo', 'Inativo'), ('negociacao', 'Em Negociação'), ('contratacao', 'Em Contratação'), ('implantacao', 'Em Implantação'), ('ativo', 'Ativo')], default='negociacao', max_length=20),
        ),
    ]
