# Generated by Django 6.0.2 on 2026-02-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inativo', 'Inativo'), ('Em Andamento', 'Em Andamento'), ('ativo', 'Ativo')], default='negociacao', max_length=20),
        ),
    ]
