# Generated by Django 6.0.2 on 2026-04-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadempresa_leadendereco_estrutura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confianca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confian?a dos Dados'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro / Endere?o'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Capta??o'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usu?rio Instagram'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N?mero'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='observacao_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Observa??o da IA'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Raz?o Social / Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em Negocia??o'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo'), ('inviavel', 'Invi?vel / N?o Avan?ou')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em Negocia??o'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo'), ('inviavel', 'Invi?vel / N?o Avan?ou')], default='novo', max_length=20),
        ),
    ]
