# Generated by Django 6.0.2 on 2026-04-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_confianca_alter_lead_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confianca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confiança dos Dados'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro / Endereço'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Captação'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário Instagram'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='observacao_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da IA'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social / Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em Negociação'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo'), ('inviavel', 'Inviável / Não Avançou')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='confianca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confiança dos Dados'),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='fonte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Captação'),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuário Instagram'),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='observacao_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da IA'),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social / Nome'),
        ),
        migrations.AlterField(
            model_name='leadempresa',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em Negociação'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo'), ('inviavel', 'Inviável / Não Avançou')], default='novo', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadendereco',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro / Endereço'),
        ),
        migrations.AlterField(
            model_name='leadendereco',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
    ]
