# Generated by Django 6.0.2 on 2026-03-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='razao_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razão Social / Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('negociacao', 'Em Negociação'), ('inativo', 'Inativo'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo')], default='negociacao', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone/WhatsApp'),
        ),
    ]
