# Generated by Django 6.0.2 on 2026-03-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_cidade_alter_lead_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo')], default='negociacao', max_length=20),
        ),
    ]
