# Generated by Django 6.0.2 on 2026-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em Negociação'), ('andamento', 'Em Andamento'), ('ativo', 'Ativo'), ('inviável', 'Inviável / Não Avançou')], default='novo', max_length=20),
        ),
    ]
