# Generated by Django 6.0.2 on 2026-03-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Automação')),
                ('slug', models.SlugField(help_text='Nome na URL (ex: robo-excel)', unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pasta_script', models.CharField(help_text='Nome da pasta dentro de automacoes/scripts/', max_length=255)),
                ('status', models.CharField(choices=[('PARADO', 'Parado'), ('RODANDO', 'Rodando'), ('ERRO', 'Erro'), ('CONCLUIDO', 'Concluído')], default='PARADO', max_length=20)),
                ('arquivo_entrada', models.FileField(blank=True, null=True, upload_to='automacoes/entradas/')),
                ('resultado_processamento', models.FileField(blank=True, null=True, upload_to='automacoes/resultados/')),
                ('ultima_execucao', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
            },
        ),
    ]
