# Generated by Django 6.0.2 on 2026-03-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automacao',
            name='progresso',
            field=models.IntegerField(default=0),
        ),
    ]
