# Generated by Django 6.0.2 on 2026-03-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ixc', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID IXC')),
                ('razao_social', models.CharField(default='', max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(default='', max_length=20, verbose_name='CNPJ/CPF')),
                ('contato_nome', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nome do Contato')),
                ('email', models.EmailField(blank=True, default='contato@exemplo.com', max_length=254, null=True, verbose_name='E-mail Principal')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Matriz', help_text='Ex: Matriz, Filial', max_length=50, verbose_name='Tipo')),
                ('cep', models.CharField(default='', max_length=20, verbose_name='CEP')),
                ('logradouro', models.CharField(default='', max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(default='S/N', max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(default='', max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(default='Fortaleza', max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='CE', max_length=2, verbose_name='UF')),
                ('login_ixc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Login IXC (PPPoE)')),
                ('filial_ixc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Filial (IXC)')),
                ('agente_id_ixc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Agente ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado')], default='pendente', max_length=15, verbose_name='Status')),
                ('data_ativacao', models.DateField(blank=True, null=True, verbose_name='Data de Ativação')),
                ('principal', models.BooleanField(default=False, verbose_name='Endereço Principal?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Endereço/Login',
                'verbose_name_plural': 'Endereços e Logins',
                'ordering': ['status', 'logradouro'],
            },
        ),
    ]
