# Generated by Django 6.0.2 on 2026-02-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='descricao',
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(default='Matriz', help_text='Ex: Matriz, Filial, Depósito', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='contato@exemplo.com', max_length=254, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(default='', max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='', max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='Fortaleza', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='CE', max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default='S/N', max_length=20, verbose_name='Número'),
        ),
    ]
