# Generated by Django 6.0.2 on 2026-03-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('rodando', 'Rodando...'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='rodando', max_length=20, verbose_name='Status')),
                ('registros_processados', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes / Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Histórico de Sincronização',
                'verbose_name_plural': 'Histórico de Sincronizações',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
