# Generated by Django 6.0.2 on 2026-02-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato_nome',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nome do Contato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='contato@exemplo.com', max_length=254, null=True, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
