# Generated by Django 6.0.2 on 2026-03-20 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_historicosincronizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ixc', models.CharField(max_length=50, verbose_name='ID IXC')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj_cpf', models.CharField(max_length=20, verbose_name='CNPJ/CPF')),
                ('dados_completos_json', models.JSONField(verbose_name='Dados Completos (Backup)')),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lixo IXC - Cliente',
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='agent_circuit_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Circuito'),
        ),
        migrations.AddField(
            model_name='historicosincronizacao',
            name='executado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='historicosincronizacao',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='automatica', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='historicosincronizacao',
            name='tipo',
            field=models.CharField(choices=[('incremental', 'Incremental'), ('total', 'Carga Total'), ('faxina', 'Faxina/Lixo')], default='incremental', max_length=20, verbose_name='Tipo de Sync'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(default='Matriz', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicosincronizacao',
            name='detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='historicosincronizacao',
            name='registros_processados',
            field=models.IntegerField(default=0, verbose_name='Registros'),
        ),
        migrations.CreateModel(
            name='EnderecoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ixc', models.CharField(max_length=150, verbose_name='Login')),
                ('agent_circuit_id', models.CharField(max_length=150, null=True, verbose_name='Circuito')),
                ('detalhes_json', models.JSONField()),
                ('cliente_excluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.clienteexcluido')),
            ],
        ),
        migrations.CreateModel(
            name='LogAlteracaoIXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ixc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Login IXC')),
                ('campo_alterado', models.CharField(max_length=100)),
                ('valor_antigo', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_alteracoes', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Log de Alteração IXC',
                'ordering': ['-data_registro'],
            },
        ),
    ]
