# Generated by Django 6.0.2 on 2026-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_endereco_campos_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='dupla_abordagem',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Dupla Abordagem'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='entrega_rb',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Entrega RB'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo_acesso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Acesso'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ipv4_bloco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco IP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='velocidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidade (Mbps)'),
        ),
    ]
