# Generated by Django 6.0.2 on 2026-03-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_endereco_estado_alter_endereco_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['status', 'logradouro'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AddField(
            model_name='endereco',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='ativo', max_length=15, verbose_name='Status'),
        ),
    ]
