# Generated by Django 6.0.2 on 2026-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_endereco_options_endereco_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=15, verbose_name='Status'),
        ),
    ]
