# Generated by Django 6.0.2 on 2026-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_endereco_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='data_ativacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Ativação'),
        ),
    ]
