# Generated by Django 6.0.2 on 2026-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_endereco_data_ativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='contato_suporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato para Suporte'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='telefone_suporte',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Telefone'),
        ),
    ]
