# Generated by Django 6.0.2 on 2026-03-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_endereco_contato_suporte_endereco_telefone_suporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='contato_suporte',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='telefone_suporte',
        ),
    ]
