# Generated by Django 6.0.2 on 2026-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_rename_campos_os_atuais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='em_os_comercial_lastmile',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Em OS Comercial | Lastmile?'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='setor_os_atual_id_ixc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Setor Atual da OS ID IXC'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='setor_os_atual_nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Setor Atual da OS'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ticket_os_atual_ixc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ticket/OS Atual IXC'),
        ),
    ]
