# Generated by Django 6.0.2 on 2026-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_historicosincronizacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='os_atual_aberta',
            field=models.BooleanField(db_index=True, default=False, verbose_name='OS Atual Aberta?'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='status_os_atual_nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Atual da OS'),
        ),
    ]
