# Generated by Django 6.0.2 on 2026-05-08 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0017_alter_historicosincronizacao_tipo'),
        ('core', '0006_emailcotacaorespostasync_emailcotacaorespostaimportacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCotacaoRespostaImportacaoAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Resposta de e-mail importada',
                'verbose_name_plural': 'Respostas de e-mail importadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.emailcotacaorespostaimportacao',),
        ),
        migrations.CreateModel(
            name='EmailCotacaoRespostaSyncAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Sync de respostas por e-mail da cotacao',
                'verbose_name_plural': 'Syncs de respostas por e-mail da cotacao',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.emailcotacaorespostasync',),
        ),
        migrations.CreateModel(
            name='HistoricoSincronizacaoAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Historico de Sincronizacao',
                'verbose_name_plural': 'Historico de Sincronizacoes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientes.historicosincronizacao',),
        ),
        migrations.CreateModel(
            name='IntegrationAuditAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Log de Integracao',
                'verbose_name_plural': 'Logs de Integracoes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.integrationaudit',),
        ),
        migrations.CreateModel(
            name='IntegrationAuditItemAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Item do Log de Integracao',
                'verbose_name_plural': 'Itens do Log de Integracao',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.integrationaudititem',),
        ),
        migrations.CreateModel(
            name='LogAlteracaoIXCAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Log de Alteracao IXC',
                'verbose_name_plural': 'Log de Alteracoes IXC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clientes.logalteracaoixc',),
        ),
        migrations.CreateModel(
            name='RegistroHistoricoAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Registro de Historico',
                'verbose_name_plural': 'Registros de Historico',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.registrohistorico',),
        ),
        migrations.CreateModel(
            name='LoginAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_informado', models.CharField(blank=True, max_length=150, verbose_name='Usuario informado')),
                ('acao', models.CharField(choices=[('login_sucesso', 'Login com sucesso'), ('login_falha', 'Falha no login'), ('logout', 'Logout')], max_length=20, verbose_name='Acao')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereco IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_login', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria de Login',
                'verbose_name_plural': 'Auditorias de Login',
                'ordering': ['-criado_em'],
            },
        ),
    ]
