# Generated by Django 6.0.2 on 2026-05-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreBackupAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('servidor', 'Backup do servidor'), ('upload', 'Upload manual')], max_length=20, verbose_name='Origem')),
                ('arquivo_nome', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('sucesso', models.BooleanField(default=False, verbose_name='Sucesso')),
                ('media_restaurada', models.BooleanField(default=False, verbose_name='Midia restaurada')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereco IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_restore_backup', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Auditoria de Restore de Backup',
                'verbose_name_plural': 'Auditorias de Restore de Backup',
                'ordering': ['-criado_em'],
            },
        ),
    ]
