# Generated by Django 6.0.2 on 2026-05-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0002_restorebackupauditoria"),
        ("partners", "0022_partnerplan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CotacaoStatusAuditoria",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_cotacao", models.CharField(blank=True, max_length=30, verbose_name="Codigo da cotacao")),
                ("codigo_lote", models.CharField(blank=True, max_length=30, verbose_name="Codigo do lote")),
                ("parceiro_nome", models.CharField(blank=True, max_length=200, verbose_name="Parceiro")),
                ("cliente_nome", models.CharField(blank=True, max_length=255, verbose_name="Cliente")),
                ("endereco_referencia", models.CharField(blank=True, max_length=255, verbose_name="Endereco")),
                ("status_anterior", models.CharField(max_length=30, verbose_name="Status anterior")),
                ("status_novo", models.CharField(max_length=30, verbose_name="Status novo")),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("alteracao_individual", "Alteracao individual"),
                            ("alteracao_lote", "Alteracao em lote"),
                            ("conversao_viavel", "Conversao de cotacao viavel"),
                            ("fechamento_automatico", "Fechamento automatico de outra cotacao"),
                        ],
                        max_length=30,
                        verbose_name="Origem",
                    ),
                ),
                ("integrou_ixc", models.BooleanField(default=False, verbose_name="Integrou com IXC")),
                ("endereco_ip", models.GenericIPAddressField(blank=True, null=True, verbose_name="Endereco IP")),
                ("user_agent", models.CharField(blank=True, max_length=500, verbose_name="User Agent")),
                ("detalhes", models.TextField(blank=True, verbose_name="Detalhes")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_status",
                        to="partners.proposal",
                        verbose_name="Cotacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_status_cotacao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditoria de Status da Cotacao",
                "verbose_name_plural": "Auditorias de Status das Cotacoes",
                "ordering": ["-criado_em"],
            },
        ),
    ]
