# Generated by Django 6.0.2 on 2026-05-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_integrationaudit_integration"),
        ("auditoria", "0003_cotacaostatusauditoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="DesativacaoAtendimentoIXCAuditoria",
            fields=[],
            options={
                "verbose_name": "Desativacao de Atendimento IXC",
                "verbose_name_plural": "Desativacao de Atendimentos IXC",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.integrationaudit",),
        ),
    ]
