# Generated by Django 6.0.2 on 2026-05-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_desativacaoatendimentoixcauditoria'),
        ('core', '0007_alter_integrationaudit_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroClienteIXCAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Cadastro de Cliente IXC',
                'verbose_name_plural': 'Cadastro de Clientes IXC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.integrationaudit',),
        ),
    ]
