# Generated by Django 6.0.2 on 2026-05-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_cadastroclienteixcauditoria'),
        ('core', '0008_alter_integrationaudit_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoLoginIXCAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Edicao de Login IXC',
                'verbose_name_plural': 'Edicao de Logins IXC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.integrationaudit',),
        ),
    ]
