# Generated by Django 6.0.2 on 2026-05-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_edicaologinixcauditoria'),
        ('core', '0009_alter_integrationaudit_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicaoAtendimentoIXCAuditoria',
            fields=[
            ],
            options={
                'verbose_name': 'Edicao de Atendimento IXC',
                'verbose_name_plural': 'Edicao de Atendimentos IXC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.integrationaudit',),
        ),
    ]
